### ISSUE TITLE
US1: User account creation

### ISSUE THREAD

**Issue by rbutera03** [rbutera03/WalkPointURI#19]
US1: User account creation
AS A new user, I WANT TO create an account SO THAT I can access the personalized features of the app.
SCENARIO:
GIVEN the user is on the signup page,
WHEN they fill out the required fields and submit,
THEN an account is created in the system WITHIN a few seconds,
AND the user receives a welcome email confirmation WITHIN 1 minute.

GIVEN the user is on the signup page,
WHEN they enter an email address that is already associated with an account,
THEN the system displays an error message (e.g., "This email is already registered. Please log in or use a different email.")

GIVEN the user is on the signup page,
WHEN they enter an email address with a domain that does not exist (e.g., user@invalid_domain.xyz),
THEN the system displays an error message (e.g., "The email address is invalid. Please check and try again.").

GIVEN the user is on the signup page,
WHEN they enter an email address in an invalid format (e.g., "userexample.com" or "user@.com"),
THEN the system displays an error message (e.g., "Please enter a valid email address.").

**Comment by keremerkmen** [comment]
US1: User account creation
AS A new user, I WANT TO create an account SO THAT I can access the personalized features of the app.
SCENARIO:
GIVEN the user is on the signup page,
WHEN they fill out the required fields and submit,
THEN an account is created in the system WITHIN a few seconds,
AND the user receives a welcome email confirmation WITHIN 1 minute.
