### ISSUE TITLE
US3: Backend setup

### ISSUE THREAD

**Issue by rbutera03** [rbutera03/WalkPointURI#21]
US3: Backend setup
AS A developer, I WANT TO set up the Firestore database and cloud functions SO THAT user data can be stored securely and efficiently.
SCENARIO:
GIVEN the project backend is empty,
WHEN I configure the Firestore schema according to the 305Soft NoSQL database standards,
THEN the system can handle user account and route data WITHIN optimal performance times.

**Comment by keremerkmen** [comment]
US3: Backend setup
AS A developer, I WANT TO set up the Firestore database and cloud functions SO THAT user data can be stored securely and efficiently.
SCENARIO:
GIVEN the project backend is empty,
WHEN I configure the Firestore schema according to the 305Soft NoSQL database standards,
THEN the system can handle user account and route data WITHIN optimal performance times.
