### ISSUE TITLE
US4: Golden Path

### ISSUE THREAD

**Issue by rbutera03** [rbutera03/WalkPointURI#22]
US4: Golden Path Main functionality 
AS A user, I WANT TO view personalized walking routes SO THAT I can navigate the campus based on my schedule.
SCENARIO:
GIVEN the user is logged in,
WHEN they access the navigation feature,
THEN the app displays walking routes based on their class schedule WITHIN a few seconds,
AND the route is shown on the customized campus map WITHIN 3 seconds.

**Comment by keremerkmen** [comment]
US4: [Golden Path] Main functionality UI/UX
AS A user, I WANT TO view personalized walking routes SO THAT I can navigate the campus based on my schedule.
SCENARIO:
GIVEN the user is logged in,
WHEN they access the navigation feature,
THEN the app displays walking routes based on their class schedule WITHIN a few seconds,
AND the route is shown on the customized campus map WITHIN 3 seconds.
