### ISSUE TITLE
US5: Create a Custom Route

### ISSUE THREAD

**Issue by rbutera03** [rbutera03/WalkPointURI#23]
AS A user,
I WANT TO create and save a personal walking route
SO THAT I can revisit the same path for future walks based on my preferences.

SCENARIO:
GIVEN the user has entered their starting point and destination,
WHEN they choose to create a personal route,
THEN the app allows the user to manually add waypoints and define the path WITHIN 10 seconds,
AND the route is saved in their profile WITHIN 5 seconds for future access.

GIVEN the user is creating a personal route,
WHEN they do not provide a route name and attempt to save,
THEN the app displays an error message (e.g., "Please enter a name for your route before saving.").

GIVEN the user is creating a personal route,
WHEN they do not select a starting  or ending point,
THEN the app prevents them from proceeding and displays an error message (e.g., "Please select both a starting and ending location to create your route.").

**Comment by keremerkmen** [comment]
US5: Supplementary Feature - Route Suggestions
AS A user, I WANT TO receive alternate walking route suggestions SO THAT I can choose the fastest or most scenic path based on my preferences.
SCENARIO:
GIVEN the user has entered their destination,
WHEN they request an alternate route,
THEN the app offers 2-3 alternate paths WITHIN 5 seconds,
AND each option is shown on the map WITHIN 2 seconds.
